name: Validate Documentation Metadata

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-doc-metadata:
    name: Validate Doc Metadata
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: validate metadata
        uses: awsdocs/aws-doc-sdk-examples-tools@9e8dd5c2225ae43d6c0f7fb7c46caf8b3a5311c2
        with:
          doc_gen_only: "False"
          strict_titles: "True"
